name: Update index.json

on:
  push:
    paths:
      - 'bacheca/**.md'

jobs:
  Update-Index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - uses: antopio26/update-index@v1.5.3
        with:
          added: ${{ steps.file_changes.outputs.files_added }}
          removed: ${{ steps.file_changes.outputs.files_removed }}
          modified: ${{ steps.file_changes.outputs.files_modified }}
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "antoniopio.maggio@live.it"
          git config --local user.name "antopio26"
          git add *.json
          git commit -m "Auto Update index.json" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
