name: Update index.json

on:
  push:
    paths:
      - 'bacheca/**'

jobs:
  Update-Index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - uses: antopio26/update-index@v1.1.3
        with:
          paths: ${{steps.file_changes.outputs.files}}
