name: Update index.json

on:
  push:
    paths:
      - 'JAK/**.md'

jobs:
  Update-Index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - uses: antopio26/update-index@v1.2.0
        with:
          added: ${{ steps.file_changes.outputs.files_added }}
          removed: ${{ steps.file_changes.outputs.files_removed }}
          modified: ${{ steps.file_changes.outputs.files_modified }}
      - name: Push repository
        run: |
          git status
          git add .
          git commit -m "Auto Update index.json files"
          git push
